language: 
    - python

os: 
    - linux

branches:
    only:
    - metadata-manager

install:
    - pip install pipenv
    - pipenv install .

script:
    - python3 -m  unittest discover tests
    - flake8 --ignore=F401
