language:
  - python
  - bash

python:
  - 3.6

os:
  - linux

install:
  - sudo apt-get install shellcheck
  - pip install flake8

before_script:
  - chmod +x setup.sh
  - . ./setup.sh
  - python3 -m pip install coverage

script:
  - flake8 .
  - shellcheck ./src/*.sh
  - python3 -m coverage run --branch -m unittest discover tests

after_success:
  - bash <(curl -s https://codecov.io/bash)