language:
  - python
  - bash

python:
  - 3.5

os:
  - linux

install:
  - sudo apt-get install shellcheck
  - pip install flake8

before_script:
  - chmod +x setup.sh
  - . ./setup.sh

script:
  - flake8 .
  - shellcheck ./src/*.sh
  - python3 -m tests.test_generate_temp_files
  - python3 -m tests.test_config
