language: 
    - python

python:
    - "3.*"

os: 
    - linux

branches:
    only:
    - metadata-manager

install:
    - pip install pipenv
    - pipenv install .
    - pip install flake8

script:
    - python3 -m  unittest discover tests
    - flake8 --ignore=F401
