language:
  - python
  - bash

python:
  - 3.5

os:
  - linux

install:
  - sudo apt-get install shellcheck
  - pip install flake8

script:
  - chmod +x setup.sh
  - . ./setup.sh
  - flake8 ./src/*.py
  - flake8 ./tests/*.py
  - shellcheck ./src/*.sh
  - python3 -m tests.test_index_generation
  - python3 -m tests.test_config
